name: Advanced CI CD pipeline
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    # schedule:
    #   - cron: "0 0 * * *"
jobs:
  python_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install coverage
          exit

      - name: Run unit tests and check coverage
        run: |
          coverage run -m unittest discover -s ./script_for_workflow
          coverage report
          coverage report --fail-under=20 # Setting 20 for test coverage

      - name: Run python script to fetch github API responses
        run: python3 ./script_for_workflow/pyscript.py
