name: Advanced CI CD pipeline
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    schedule:
      - cron: "0 0 * * *"
jobs:
  python_script:
    runs-on: ubuntu-latest
    steps:
      - name: Check Python version
        run: python3 --version

      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Runs python external script
        run: |
          chmod +x ./pyscript.py
          ./pyscript.py
