name: Advanced CI CD pipeline
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    # schedule:
    #   - cron: "0 0 * * *"
jobs:
  python_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run python script to fetch github API responses
        run: python3 ./script-for-workflow/pyscript.py
