name: Advanced CI CD pipeline
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    # schedule:
    #   - cron: "0 0 * * *"
jobs:
  python_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install flake8 black coverage

      - name: Lint with flake8
        run: |
          flake8 ./script_for_workflow --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 ./script_for_workflow --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      - name: Format with black
        run: |
          black --check ./script_for_workflow

      - name: Run unit tests and check coverage
        run: |
          coverage run -m unittest discover -s ./script_for_workflow
          coverage report
          coverage report --fail-under=90

      - name: Run python script to fetch github API responses
        run: python3 ./script_for_workflow/pyscript.py
