name: Advanced CI CD pipeline
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    schedule:
      - cron: "0 0 * * *"
jobs:
  python_script:
    runs-on: ubuntu-latest
    steps:
      - name: Check Python version
        run: python3 --version
      - name: Runs python external script
        run: ./pyscript.py
